### ISSUE TITLE
security: consider implementing security policy and enable Dependabot Auto PR

### ISSUE THREAD

**Issue by gaukas** [erikziyunchi/water-rs#25]
As of 01/26/2024, there are 4 outstanding security alerts with one of them being rated as High severity. We require a much responsive model in terms of patching security vulnerabilities. 

I would recommend adding a security policy clarifying what do we (plan to) provide and enabling automated PR by Dependabot helping patching the vulns.

**Comment by erikziyunchi** [comment]
`wasmtime` related upgrades always require some changes in the code as they sometimes change their APIs 🤕.

**Comment by gaukas** [comment]
And I see this issue has been addressed in #26 and following dependabot-related PRs, now closing as completed!
